/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is auto-generated by Next.js on `next dev` / `next build`.
// Do not edit it by hand — it is regenerated automatically and should stay
// out of manual review diffs. It is committed here only so `tsc` has a
// valid starting point before the first `next dev` run regenerates it.
