import type { Config } from "tailwindcss";

// Design tokens for Profitabilly (approved direction, Mini-Sprint 36):
// minimalist, professional, numbers-first. Token NAMES are role-based
// and stable (ink, paper, rule, profit, muted, danger…), so pages that
// already use them pick up the new values without being edited.
// See ARCHITECTURE.md → "Design system" for usage rules.
const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    // lib/finance/money.ts returns Tailwind class names (profitToneClass).
    // Without this glob those classes are only generated by accident, when
    // the same string happens to appear in a scanned file.
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Primary navy: text, primary buttons, focus ring.
        ink: {
          DEFAULT: "#0F172A",
          hover: "#1E293B", // secondary slate — primary button hover
          soft: "#334155", // slate — strong secondary text (inactive nav)
        },
        paper: "#F8FAFC", // page background
        surface: "#FFFFFF", // cards, inputs, nav bar
        rule: {
          DEFAULT: "#E2E8F0", // subtle dividers and card borders
          // Form-control / secondary-button boundary. #E2E8F0 on white is
          // ~1.2:1, too faint to see where an input is; this is ~3.2:1.
          strong: "#8390A5",
        },
        muted: "#64748B", // secondary text (4.6:1 on paper; never on tinted fills)
        // Positive / profit. DEFAULT (#16A34A) is for fills, tints and
        // borders — it is only ~3.3:1 as text on white, so text uses
        // `strong` (~5:1).
        profit: {
          DEFAULT: "#16A34A",
          strong: "#15803D",
          bright: "#10B981", // emerald — approved, reserved for accents/charts, unused so far
        },
        danger: "#DC2626", // negative values, errors, destructive actions (4.8:1 as text)
        // Warning. DEFAULT (#D97706) is ~3.2:1 as text on white — use it for
        // fills/borders/icons; use `strong` when it must be readable text.
        warning: {
          DEFAULT: "#D97706",
          strong: "#B45309",
        },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      fontSize: {
        // Approved page-heading size (28/32). Named, not applied to pages
        // yet — existing pages still use text-2xl/3xl until each screen's
        // own redesign sprint. Section = text-lg, body = text-sm,
        // metadata = text-xs (Tailwind defaults already match the spec).
        page: ["1.75rem", { lineHeight: "2rem", letterSpacing: "-0.015em" }],
      },
    },
  },
  plugins: [],
};

export default config;
